version: '3'
services:
  robot01:
    image: roschain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot01
    networks:
      - robot01
    environment:
      - ROBOT_NAME=uav-1
      - ROBOT_TYPE=uav
      - MQTT_HOST=${SIMULATION_HOST}
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=1
      - ROS_MASTER_URI=http://${SIMULATION_HOST}:11311
      - GAZEBO_MASTER_URI=http://${SIMULATION_HOST}:11345
    volumes:
      - ./robots/robot04:/robot_ws/src/multirobot_sim/files

  robot02:
    image: roschain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot02
    networks:
      - robot02
    environment:
      - ROBOT_NAME=ugv-2
      - ROBOT_TYPE=ugv
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=1
      - ROS_MASTER_URI=http://${SIMULATION_HOST}:11311
      - GAZEBO_MASTER_URI=http://${SIMULATION_HOST}:11345
    volumes:
      - ./robots/robot03:/robot_ws/src/multirobot_sim/files

networks:
  robot01:
  robot02:
