version: '3'
services:
  robot01:
    image: roschain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${ROBOT_NAME}
    environment:
      - ROBOT_NAME=${ROBOT_NAME}
      - ROBOT_TYPE=${ROBOT_TYPE}
      - MQTT_HOST=${SIMULATION_HOST}
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=1
      - ROS_MASTER_URI=http://${SIMULATION_HOST}:11311
      - GAZEBO_MASTER_URI=http://${SIMULATION_HOST}:11345
    volumes:
      - ./robots/${ROBOT_NAME}:/robot_ws/src/multirobot_sim/files
 