version: '3'
services:
  robot01:
    image: roschain:latest
    networks:
      - robot01
    environment:
      - ROBOT_NAME=uav01
      - ROBOT_TYPE=uav
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
  robot02:
    image: roschain:latest
    networks:
      - robot02
    environment:
      - ROBOT_NAME=ugv01
      - ROBOT_TYPE=ugv
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
  robot03:
    image: roschain:latest
    networks:
      - robot03
    environment:
      - ROBOT_NAME=ugv02
      - ROBOT_TYPE=ugv
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
  robot04:
    image: roschain:latest
    networks:
      - robot04
    environment:
      - ROBOT_NAME=uav02
      - ROBOT_TYPE=uav
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker

  robot05:
    image: roschain:latest
    networks:
      - robot05
    environment:
      - ROBOT_NAME=ugv03
      - ROBOT_TYPE=ugv
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
  robot06:
    image: roschain:latest
    networks:
      - robot06
    environment:
      - ROBOT_NAME=uav03
      - ROBOT_TYPE=uav
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker

  robot07:
    image: roschain:latest
    networks:
      - robot07
    environment:
      - ROBOT_NAME=ugv04
      - ROBOT_TYPE=ugv
      - MQTT_HOST=mosquittoo
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=10
      - MIN_NODES_NUM=6
      - ROS_MASTER_URI=http://rosmaster:11311
      - GAZEBO_MASTER_URI=http://rosmaster:11345
      - TIMEOUT_INTERVAL=60
#    volumes:
#      - ~/data:/robot_ws/src/multirobot_sim/files
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == worker
 
  mosquittoo:
    image: eclipse-mosquitto
    container_name: mosquittoo
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ~/mosquitto/data:/etc/mosquitto
      - ~/mosquitto/config:/mosquitto/config
    networks:
      - robot01
      - robot02
      - robot03
      - robot04
      - robot05
      - robot06
      - robot07
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager

  rosmaster:
    container_name: rosmaster
    image: simulation_setup:latest
    networks:
      - robot01
      - robot02
      - robot03
      - robot04
      - robot05
      - robot06
      - robot07
    environment:
      - WORLD_FILE=/root/robot_ws/src/multirobot_sim/worlds/testworld.world
      - MAP_FILE=/root/robot_ws/src/multirobot_sim/maps/map.yaml
      - LAUNCH_FILE=7
      - ROS_MASTER_URI=http://rosmaster:11311
    restart: always
    ports:
      - "8080:8080"
      - "11311:11311"
      - "11345:11345"
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager


networks:
  robot01:
  robot02:
  robot03:
  robot04:
  robot05:
  robot06:
  robot07: